kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: kaizoku
version: 0.2.0
appVersion: 1.7.0
description: A self-hosted manga downloader.
home: https://truecharts.org/charts/incubator/kaizoku
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kaizoku.png
deprecated: false
sources:
  - https://github.com/truecharts/charts/tree/master/charts/unstable/kaizoku
  - https://github.com/zyradyl/kaizoku
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
keywords:
  - kaizoku
dependencies:
  - name: common
    version: 17.1.4
    repository: https://library-charts.truecharts.org
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: redis
    version: 10.0.1
    repository: https://deps.truecharts.org
    condition: redis.enabled
    alias: ""
    tags: []
    import-values: []
annotations:
  max_scale_version: 23.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.13"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: incubator
type: application
