image:
  repository: ghcr.io/zyradyl/kaizoku
  pullPolicy: IfNotPresent
  tag: v1.7.0@sha256:fa87a247256888981acaedac99631e50729957a73e0729a6e8d6a6e397f5809a
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KAIZOKU_PORT: "{{ .Values.service.main.ports.main.port }}"
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PORT: 6379
persistence:
  config:
    enabled: true
    mountPath: "/config"
  logs:
    enabled: true
    mountPath: "/logs"
  data:
    enabled: true
    mountPath: "/data"
cnpg:
  main:
    enabled: true
    user: kaizoku
    database: kaizoku
redis:
  enabled: true
portal:
  open:
    enabled: true
